default:
   target: dev
   outputs:
     dev:
       type: bigquery
       method: service-account-json
       project: "{{ env_var('BQ_PROJECT') }}"
       dataset: "{{ env_var('BQ_DATASET') }}"
       location: "{{ env_var('BQ_LOCATION') }}"
       threads: 1
       timeout_seconds: 300
       retries: 1

       keyfile_json:
        type: service_account
        project_id: "{{ env_var('BQ_PROJECT') }}"
        private_key_id: "{{ env_var('PROF_PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('PROF_PRIVATE_KEY') }}"
        client_email: "{{ env_var('PROF_CLIENT_EMAIL') }}"
        client_id: "{{ env_var('PROF_CLIENT_ID') }}"
        auth_uri: https://accounts.google.com/o/oauth2/auth
        token_uri: https://oauth2.googleapis.com/token
        auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        client_x509_cert_url: "{{ env_var('PROF_CLIENT_CERT_URL') }}"

     pr_db:
       type: bigquery
       method: service-account-json
       project: "{{ env_var('BQ_PROJECT') }}"
       dataset: "pr_db"       
       location: "{{ env_var('BQ_LOCATION') }}"
       threads: 1
       timeout_seconds: 300
       retries: 1

       keyfile_json:
        type: service_account
        project_id: "{{ env_var('BQ_PROJECT') }}"
        private_key_id: "{{ env_var('PROF_PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('PROF_PRIVATE_KEY') }}"
        client_email: "{{ env_var('PROF_CLIENT_EMAIL') }}"
        client_id: "{{ env_var('PROF_CLIENT_ID') }}"
        auth_uri: https://accounts.google.com/o/oauth2/auth
        token_uri: https://oauth2.googleapis.com/token
        auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        client_x509_cert_url: "{{ env_var('PROF_CLIENT_CERT_URL') }}"
