default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('BQ_PROJECT') }}"
      dataset: "{{ env_var('BQ_DATASET') }}"
      location: "{{ env_var('BQ_LOCATION') }}"
      threads: 4
      timeout_seconds: 300
      retries: 1
      # keyfile: "/Users/tin/secrets/gcp-sa-storage-bq.json"
      
      keyfile_json:
        type: "service_account"
        project_id: "{{ env_var('BQ_PROJECT') }}"
        private_key_id: "{{ env_var('BQ_PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('BQ_PRIVATE_KEY') }}"
        client_email: "{{ env_var('BQ_CLIENT_EMAIL') }}"
        client_id: "{{ env_var('BQ_CLIENT_ID') }}"
        auth_uri: "{{ env_var('BQ_AUTH_URI') }}"
        token_uri: "{{ env_var('BQ_TOKEN_URI') }}"
        auth_provider_x509_cert_url: "{{ env_var('BQ_AUTH_PROVIDER_X509_CERT_URL') }}"
        client_x509_cert_url: "{{ env_var('BQ_CLIENT_X509_CERT_URI') }}"

    pr_db:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('BQ_PROJECT') }}"
      dataset: "pr_db"       
      location: "{{ env_var('BQ_LOCATION') }}"
      threads: 1
      timeout_seconds: 300
      retries: 1

      keyfile_json:
        type: service_account
        project_id: "{{ env_var('BQ_PROJECT') }}"
        private_key_id: "{{ env_var('BQ_PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('BQ_PRIVATE_KEY') }}"
        client_email: "{{ env_var('BQ_CLIENT_EMAIL') }}"
        client_id: "{{ env_var('BQ_CLIENT_ID') }}"
        auth_uri: "{{ env_var('BQ_AUTH_URI') }}"
        token_uri: "{{ env_var('BQ_TOKEN_URI') }}"
        auth_provider_x509_cert_url: "{{ env_var('BQ_AUTH_PROVIDER_X509_CERT_URL') }}"
        client_x509_cert_url: "{{ env_var('BQ_CLIENT_X509_CERT_URI') }}"
