name: BQ DBT

on:
  pull_request:
    branches:
      - master
      - develop
      - workflow
    paths:
      - 'dbt/**'
  push:
    branches:
      - master
      - develop
      - workflow
    paths:
      - 'dbt/**'

concurrency:
  group: ${{ github.ref }}

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write

jobs:
  check:
    name: Check for DBT changes
    runs-on: ubuntu-latest
    outputs:
      dbt_changes: ${{ steps.dbt_changes.outputs.dbt_changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: changed
        uses: dorny/paths-filter@v2
        name: Get Changed Files
        with:
          filters: |
            dbt:
              - 'dbt/**'

      - name: Debug Changed Files
        run: |
          echo "Changed files: ${{ steps.changed.outputs.dbt }}"

      - id: dbt_changes
        run: |
          if [[ -n "${{ steps.changed.outputs.dbt }}" ]]; then
            echo "dbt_changes=true" >> $GITHUB_ENV
            echo "DBT changes found in ${{ steps.changed.outputs.dbt }}"
          else
            echo "dbt_changes=false" >> $GITHUB_ENV
          fi

      - name: Set DBT_CHANGES output
        run: echo "dbt_changes=${{ env.dbt_changes }}" >> $GITHUB_OUTPUT

      - name: Echo DBT changes status
        run: |
          echo "DBT changes status: ${{ steps.dbt_changes.outputs.dbt_changes }}"

  apply:
    name: Deploy DBT changes
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Echo DBT changes status
        run: |
          echo "DBT changes status: ${{ needs.check.outputs.dbt_changes }}"

      - name: Proceed with deployment if DBT changes detected
        if: ${{ needs.check.outputs.dbt_changes }} == 'true'
        run: echo "DBT changes detected. Proceeding with deployment."

      - name: Skip deployment if no DBT changes detected
        if: ${{ needs.check.outputs.dbt_changes }} != 'true'
        run: echo "No DBT changes detected. Skipping deployment."
