name: BQ DBT

on:
  pull_request:
    branches:
      - main  
    paths:
      - 'dbt/**'
  push:
    branches:
      - main
    paths:
      - 'dbt/**'

concurrency:
  group: ${{ github.ref }}

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write

# Environment Variables used in profiles.yml

env:
  BQ_PROJECT: ${{ secrets.BQ_PROJECT }}
  BQ_DATASET: ${{ secrets.BQ_DATASET }}
  BQ_DATASET_PD: ${{ secrets.BQ_DATASET_PD }}
  BQ_KEYFILE_JSON: ${{ secrets.BQ_KEYFILE_JSON }}
  BQ_LOCATION: ${{ secrets.BQ_LOCATION }}
  BQ_PRIVATE_KEY: ${{ secrets.BQ_PRIVATE_KEY }}
  BQ_PRIVATE_KEY_ID: ${{ secrets.BQ_PRIVATE_KEY_ID }}
  BQ_CLIENT_EMAIL: ${{ secrets.BQ_CLIENT_EMAIL }}
  BQ_CLIENT_ID: ${{ secrets.BQ_CLIENT_ID }}
  BQ_AUTH_URI: ${{ secrets.BQ_AUTH_URI }}
  BQ_TOKEN_URI: ${{ secrets.BQ_TOKEN_URI }}
  BQ_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.BQ_AUTH_PROVIDER_X509_CERT_URL }}
  BQ_CLIENT_X509_CERT_URI: ${{ secrets.BQ_CLIENT_X509_CERT_URI }}

jobs:
  check:
    name: Check for DBT changes
    runs-on: ubuntu-latest
    outputs:
      dbt_changes: ${{ steps.set_output.outputs.dbt_changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: changed
        uses: dorny/paths-filter@v2
        name: Get Changed Files
        with:
          filters: |
            dbt:
              - 'dbt/**'

      - name: Echo Changed Files
        run: |
          echo "Changed files: ${{ steps.changed.outputs.dbt }}"

      - id: dbt_changes
        run: |
          if [[ -n "${{ steps.changed.outputs.dbt }}" ]]; then
            echo "dbt_changes=TRUE" >> $GITHUB_ENV
            echo "DBT changes found in ${{ steps.changed.outputs.dbt }}"
          else
            echo "dbt_changes=false" >> $GITHUB_ENV
          fi

      - id: set_output
        name: Set DBT_CHANGES Output
        run: echo "dbt_changes=${{ env.dbt_changes }}" >> $GITHUB_OUTPUT

  apply:
    name: Deploy DBT Changes
    needs: check
    uses: endrit-berisha/dbt-common/.github/workflows/deploy-dbt.yml@main
    secrets:
      BQ_KEYFILE_JSON: ${{ secrets.BQ_KEYFILE_JSON }} 
      BQ_PROJECT: ${{ secrets.BQ_PROJECT }}
      BQ_DATASET: ${{ secrets.BQ_DATASET }}
      BQ_DATASET_PD: ${{ secrets.BQ_DATASET_PD }}
    